Insert into genre values
(DEFAULT,'Action'),
(DEFAULT,'Adventure'),
(DEFAULT,'Comedy'),
(DEFAULT,'Cooking'),
(DEFAULT,'Drama'),
(DEFAULT,'Ecchi'),
(DEFAULT,'English Novel'),
(DEFAULT,'Fantasy'),
(DEFAULT,'Game'),
(DEFAULT,'Harem'),
(DEFAULT,'Historical'),
(DEFAULT,'Horror'),
(DEFAULT,'Isekai'),
(DEFAULT,'Korean Novel'),
(DEFAULT,'Josei'),
(DEFAULT,'Magic'),
(DEFAULT,'Martial Arts'),
(DEFAULT,'Mature'),
(DEFAULT,'Mecha'),
(DEFAULT,'Military'),
(DEFAULT,'Misunderstanding'),
(DEFAULT,'Mystery'),
(DEFAULT,'One shot'),
(DEFAULT,'Otome Game'),
(DEFAULT,'Parody'),
(DEFAULT,'Psychological'),
(DEFAULT,'Romance'),
(DEFAULT,'School Life'),
(DEFAULT,'Science Fiction'),
(DEFAULT,'Seinen'),
(DEFAULT,'Shoujo'),
(DEFAULT,'Shounen'),
(DEFAULT,'Slice of Life'),
(DEFAULT,'Slow Life'),
(DEFAULT,'Sports'),
(DEFAULT,'Super Power'),
(DEFAULT,'Supernatural'),
(DEFAULT,'Suspense'),
(DEFAULT,'Tragedy'),
(DEFAULT,'Wars'),
(DEFAULT,'Web Novel'),
(DEFAULT,'Workplace');

Insert into users (user_id, username, mail, gender, password, birth_year)
values 
(DEFAULT,'Phu siuuu','phunguyenduc99@gmail.com','Male','phudeptrai',2005),
(DEFAULT,'Luận iie','phuduc030303@gmail.com','Male','luanthichflex1234',2006),
(DEFAULT,'Japan England','labanthannhat2@gmail.com','Other','0ronaldosiu0',1998),
(DEFAULT,'Hiển Chu','labanthannhat3@gmail.com','Male','123456789',2002),
(DEFAULT,'Duy Nguyễn Trọng Khánh','labanthannhat4@gmail.com','Male','987654321',2002),
(DEFAULT,'Phạm Mai Chi','chi.pm214998@sis.hust.edu.vn','Female','bechi8tuoi',2004),
(DEFAULT,'Người dùng thích che tên','usermail1@gmail.com','Male','userpass123',2002),
(DEFAULT,'Giấu tên 1','usermail2@gmail.com','Male','userpass124',2007),
(DEFAULT,'Giấu tên 2','usermail3@gmail.com','Other','userpass125',2003),
(DEFAULT,'Tên người dùng','usermail4@gmail.com','Male','userpass126',2002),
(DEFAULT,'Giấu tên 3','usermail5@gmail.com','Male','userpass127',2004),
(DEFAULT,'Giấu tên 4','usermail6@gmail.com','Female','userpass128',1998),
(DEFAULT,'Giấu tên 5','usermail7@gmail.com','Male','userpass129',1999),
(DEFAULT,'Giấu tên 6','usermail8@gmail.com','Male','userpass130',1997),
(DEFAULT,'Giấu tên 7','usermail9@gmail.com','Other','userpass131',2008),
(DEFAULT,'Giấu tên 8','usermail10@gmail.com','Male','userpass132',2008),
(DEFAULT,'Giấu tên 9','usermail11@gmail.com','Male','userpass133',1997),
(DEFAULT,'Giấu tên 10','usermail12@gmail.com','Female','userpass134',2000),
(DEFAULT,'Giấu tên 11','usermail13@gmail.com','Male','userpass135',2007),
(DEFAULT,'Giấu tên 12','usermail14@gmail.com','Male','userpass136',2001);


Insert into novel values
(DEFAULT,6,'Rifujin na Magonote','2012','Mushoku Tensei - Isekai Ittara','Một otaku vô công rồi nghề 34 tuổi bị đuổi ra khỏi nhà bởi chính gia đình của mình. Nhận ra cuộc đời của bản thân đã lâm vào ngõ cụt cũng như là sự rác rưởi, vô dụng của bản thân; anh ta ước rằng phải chi bản thân khi xưa vượt qua được giai đoạn đen tối của cuộc đời thì bây giờ có lẽ mọi chuyện đã khác. Đúng vào khoảnh khắc hối tiếc đó, anh thấy 1 chiếc xe tải chạy với vận tốc lớn đang lao đến 3 học sinh trung học gần đó. Gom tất cả sức lực còn lại, anh ta cứu được 3 học sinh kia tuy nhiên lại phải bỏ mạng của chính bản thân mình dưới bánh chiếc xe tải đó. Khi mở mắt ra, anh nhận ra rằng mình đã được đầu thai ở thế giới của gươm giáo và phép thuật song hành tồn tại dưới cái tên Rudeus Greyrat. Dưới hình hài mới ở một thế giới mới, Rudeus tự khẳng định với bản thân " Lần này mình sẽ thực sự sống đến tận cùng cuộc sống này mà không hề tiếc nuối". Và như thế, cuộc hành trình của anh bắt đầu.',283259,0,null,'https://i.docln.net/lightnovel/covers/s139-3ce3273e-0659-44b9-a0f9-5c4a3f6604c5-m.jpg'),
(DEFAULT,6,'Baba Okina','2015','Kumo Desu Ga Nani Ka','Trích lời tác giả: tất cả nội dung của truyện là dòng suy nghĩ của nhân vật, thế nên nếu có sự hiểu nhầm gì đó thì đó là lỗi nhân vật, không phải lỗi tác giả" - Hay lỗi của trans. Câu chuyện kể về một bé nhện dễ thương bị lạc vào trong một dungeon cấp cao và phải liều mạng để bảo vệ tính mạng và sự trong sạch(lol) của mình khỏi lũ quái vật ở đó.',39304,0,null,'https://3.bp.blogspot.com/-coc62nTZN9M/WO2v-JFMCuI/AAAAAAAAKBE/Kb8JLmHVElw/w215/series_259.jpg'),
(DEFAULT,3,'Fuse','2013','Tensei Shitara Slime datta ken','Một thanh niên ( 37 tuổi vẫn còn tem) bị đâm bởi tên cướp đang trên đường tháo chạy sau khi cứu (kouhai) đồng nghiệp lẫn người tình của anh ta sang hai bên. Khi anh ấy nằm sấp mặt chờ chết, máu chảy đầm đìa dưới dất, anh ta nghe thấy một tiếng nói. Tiếng nói này lạ lẫm và diễn giải nỗi uất hận khi chết mà còn chưa được ""nện"" lần nào bằng cách cho anh ấy kỹ năng đặc biệt [Đại Hiền Nhân]!
Có phải anh ta đang bị đem ra làm trò cười?',220386,0,null,'https://i.docln.net/lightnovel/covers/s424-f8ee7ddd-d0d0-4f67-bb13-33667bbeb90d-m.jpg'),
(DEFAULT,1,'Yagami Kagami','2015','Shimotsuki wa Mob ga Suki','Nếu đây là một bộ romcom thông thường, có lẽ tôi sẽ chỉ là một nhân vật làm nền không hơn không kém.

Đứa em kế, cô bạn thân, và cả bạn thuở nhỏ, giờ đây ai nấy đều say đắm cái tên đào hoa kia cả rồi. Không cần làm gì, chỉ thở thôi cũng được yêu mến, thản nhiên khiến những người con gái quan trọng với tôi rơi vào harem, tên nhân vật chính đó giờ đang vui vẻ tận hưởng tuổi thanh xuân của mình.

Như một nhân vật phụ, đáng lẽ tôi chỉ có thể ngồi ở xó lớp mà quan sát nhân vật chính từ xa... vậy mà, cô ấy đã phát hiện ra tôi.

Bất kể có là bạn thuở nhỏ của nhân vật chính, với thân phận như là nữ chính, người con gái đó vẫn chọn tôi. Bình thường im lìm chẳng nói gì, biểu cảm cũng không có, thế mà chỉ với tôi thì cô cười nói luôn miệng.

Cô bảo tôi đặc biệt, hơn cả nhân vật chính kia, dù tôi chỉ là một thằng nhân vật nền...

Đây là câu chuyện về tôi, một tên nhân vật nền tẻ nhạt.

Được kể dưới góc nhìn meta, một câu chuyện romcom về nhân vật nền được Shimotsuki-san đem lòng yêu mến.',21275,0,null,'https://i.docln.net/lightnovel/covers/s11586-2eeb39b0-edcd-4d34-8bd7-4144c9e83f8c-m.jpg'),
(DEFAULT,2,'Ryo Shirakome','2015','Arifureta Shokugyou de','Một nhân vật được xem là vô dụng như Nagumo Hajime sẽ không thể ngờ rằng có một ngày cùng cả lớp được triệu hồi sang một thế giới khác, mang trong mình "Thiên chức" nhất định nhằm giải cứu Loài người thoát khỏi họa diệt vong. Điều gì đang chờ đợi cậu ở thế giới mới ấy? Liệu Hajime có thể lột xác trở thành con người mới được không?',60819,0,null,'https://i.docln.net/lightnovel/covers/s767-392eace6-14cc-438f-bc76-90b8351f609c-m.jpg'),
(DEFAULT,1,'Shu','2017','Maou Gakuin no Futekigousha ~Shijou Saikyou no Maou no Shiso, Tensei shite Shison tachi no Gakkou e Kayou~','Sau một thời gian dài đối địch với con người, tinh linh và cả những vị thần, trải qua vô vàn trận chiến và xung đột, Quỷ vương Arnos đã trở nên chán ngấy và mệt mỏi với tất cả những điều đó, và bắt đầu mong mỏi một thế giới hòa bình. Vì vậy, gã quỷ vương ấy đã quyết định hi sinh thân mình để xây dựng bức tường phân chia thế giới, chấm dứt cuộc chiến tranh, và chuyển sinh đến 2000 năm sau.
Tuy nhiên, những gì chờ đợi cậu ta sau khi tái sinh là một thế giới vì quá quen với sự bình an mà con cháu của cậu trở nên quá yếu ớt , ma thuật sụt giảm nghiêm trọng, và những đại ma pháp thì hầu như biến mất.
Arnos theo học tại Học viện Quỷ vương - nơi được thành lập để tìm bất kỳ học viên nào có thể là tái sinh của quỷ vương, nhưng khả năng của cậu ta quá phi thường đến mức những người trong học viện không thể đánh giá đúng khả năng của cậu ta, vì vậy Arnos bị mọi người gắn cho cái mác là “Kẻ không phù hợp”. Bị đánh giá thấp và xa lánh bởi hầu hết mọi người ở đó, nhưng rồi cậu cũng đã gặp được một cô gái có thái độ thân thiện với mình, Misha, là thuộc hạ, cũng như đồng chí đầu tiên của cậu trong thời đại này. Cả hai cùng chung một mục tiêu, phấn đấu leo lên đỉnh của hệ thống phân cấp quỷ để một ngày không xa đòi lại danh hiệu và địa vị đã từng là của cậu.',370503,0,null,'https://i.docln.net/lightnovel/covers/s3601-c1361136-16b0-4692-b703-c8a5e0da67a0-m.jpg'),
(DEFAULT,2,'Kugane Maruyama','2010','Overlord','      Câu chuyện bắt đầu trong những giây phút cuối tại tại Yggdrasil, một game online đình đám sắp phải đóng cửa. Nhân vật chính Momonga của chúng ta quyết định ở lại đến tận những phút cuối cùng với trò chơi yêu thích của mình và chờ server down. Bất ngờ, server không shutdown và Momonga bị mắc kẹt trong nhân vật của chính mình và "xuyên việt" tới thế giới khác. “Overlord hùng mạnh” giờ đây lại tiếp tục đi khám phá thế giới mới và đối mặt với những thử thách mới. Không gia đình, bạn bè, địa vị xã hội, người đàn ông bình thường này sẽ cố gắng hết sức để thống trị thế giới mới này.',383288,0,null,'https://i.docln.net/lightnovel/covers/s253-2e5b9953-dbdb-41b1-8a98-cf27c12a11b4-m.jpg'),
(DEFAULT,8,'Hiro Ainana','2013','Death March kara Hajimaru Isekai Kyusoukyoku','     Suzuki, một lập trình viên trưởng thành, đang làm việc và ngủ thức dậy đột nhiên chú ý rằng cậu bị ném vào thế giới khác khi đang mặc một bộ quần áo bình thường ở cấp độ 1. Cậu đạt được cấp độ cao và kho báu sau khi sử dụng phép thuật-sẵn-có-3 lần, Mưa Thiên Thạch, chỉ với một lần và lên cấp thánh . Sau đó việc cậu dự định làm ở thế giới khác là một “chuyến du hành tham thú ngắm cảnh”? Gặp gỡ ba cô gái người thú, chị em gái tóc tím và đen xinh đẹp và một cô gái yêu tinh tóc vàng kì dị cùng với rất nhiều người trên chuyến du hành của cậu sau này xuất hiện và gia nhập dàn harem. Dù phải chiến đấu với ma quái và chúa quỉ, đây vẫn là câu chuyện viễn tưởng ấm áp xúc động.',383760,0,null,'https://i.docln.net/lightnovel/covers/s219-9647c1a2-8244-4747-a9d0-018dda2341cf-m.jpg'),
(DEFAULT,8,'Daisuke Aizawa','2016','Tensei Shitara Kendeshita','Khi nhận ra thì ... tôi đang ở 1 thế giới khác. Tôi đã trở thành 1 thanh kiếm, Dafuq? Chuyện gì thế này? Chỗ tôi tỉnh dậy sao lại toàn quái vật thế này. Tôi liền bay đi kiếm ngay 1 cộng sự cho mình (tuyển gái only, anh hùng đẹp trai mời đi chỗ khác). Một viên ma pháp thạch à? Tôi có được kĩ năng mới nhờ hấp thụ nó? Có vẻ hay đấy, mau đưa tôi thêm nào! Ừ tất nhiên là nhà ngươi sẽ không cho rồi, nhưng ta vẫn sẽ lấy nó, hahaha!

A, bị kẹt rồi. Trò đùa gì thế này? Ha, cô bé tai mèo đằng kia ơi, kéo anh ra với! Hể? Em đang bị ma thú tấn công sao!? Được lắm, cứ để đó cho anh! Cơ mà kéo anh ra cái đã!

Đây là câu chuyện của tôi, người không hiểu do đâu mà tái sinh thành một thanh kiếm, cùng phiêu lưu với một thiếu nữ tai mèo và cùng cô bé trưởng thành hơn từng ngày.',56668,0,null,'https://i.docln.net/lightnovel/covers/s787-8ae84f4f-4cc8-4acd-914d-72682df9e28e-m.jpg'),
(DEFAULT,20,'Miku','2017','Phá Đảo Dị Giới Cùng Nữ Thần','     Makoto Takatsuki là một học sinh trung học bình thường và game thủ RPG hạng nặng. Tuy nhiên, "sự bình thường" đó bỗng nhiên biến mất khi cả lớp của cậu dính vào một vụ tai nạn xe buýt và bị dịch chuyển đến thế giới khác! Các vị thần quyền năng cai trị vùng đất kỳ lạ của ma thuật và quái vật này. Tất cả mọi người khi đến đều được ban phước với các chỉ số mạnh mẽ lẫn kỹ năng độc đáo. Chà, không hoàn toàn như vậy. Chỉ số của Makoto hóa ra rất thảm hại và kỹ năng của cậu là siêu yếu so với các bạn cùng lớp... Cậu thậm chí còn bị mắc kẹt với tư cách là một pháp sư tập sự. Tệ hơn nữa, cậu chỉ còn sống được thêm có mười năm! May mắn thay, Makoto sớm gặp một nữ thần nhỏ tên là Noah, người xuất hiện trong những giấc mơ của Makoto và yêu cầu cậu trở thành tín đồ đầu tiên của mình. Với sự giúp đỡ từ chúc phúc của Noah và một thần khí, Makoto tìm cách trở nên đủ mạnh để có thể giải cứu nữ thần khỏi ngục tối nơi cô bị mắc kẹt. Thông qua việc luyện tập chăm chỉ và sử dụng những kỹ năng yếu kém của mình bằng những cách thức "không chính thống", Makoto đã chứng minh được rằng, ngay cả khi quẩy ở độ khó cao nhất, một người chơi RPG vẫn sẽ luôn quyết tâm phá đảo game cho bằng được!',172433,0,null,'https://i.docln.net/lightnovel/covers/s6947-428a3d9d-49ab-4b08-a451-1096e68cffc2-m.jpg'),
(DEFAULT,15,'Miku','2018','In no jitsury okusha ni naritakute!','      Như bao người ngưỡng mộ những anh hùng khi còn nhỏ, nhân vật chính của chúng ta lại ngưỡng mộ những con người trong bóng tối. Sau khi giấu đi khả năng thật sự và sống 1 cuộc đời tầm thường của 1 thường dân vào ban ngày trong khi trải qua những khóa huấn luyện điên rồ vào ban đêm, anh ta cuối cùng cũng được chuyển sinh sang thê giới khác. Người đàn ông ấy, người mà chỉ phô diễn sức mạnh trong bóng tối,những người hầu cận, và cùng với đó là tổ chức lớn mạnh của anh…
Đây là câu chuyện về một chàng trai, người luôn khao khát sức mạnh trong màn đêm, trị vì thế giới ngầm ở thế giới khác.',405266,0,null,'https://i.docln.net/lightnovel/covers/s3569-4f9d3270-6d42-4301-8ad7-761e917fc3b6-m.jpg'),
(DEFAULT,13,'Himawari','2019','Tensei shitara doragon no tamago datta ~ saikyō igai mezasane ~e ~','    Tôi tỉnh đậy ở một khu rừng vô danh trong hình dạng một quả trứng.
Nơi này giống như một thế giới giả tưởng, những sinh vật kỳ lạ và hung hãn khắp xung quanh. Giống như trong game, dường như tôi có thể kiểm tra chỉ số của tôi và kẻ thù.
Tôi muốn săn những con quái vật, thu thập danh hiệu để lên cấp và tiến hóa trở thành một con rồng mạnh mẽ hơn.
Rồi tôi nghe thấy một giọng nói bí ẩn ở trong đầu mình: “Hãy hướng đến mục tiêu trở thành kẻ mạnh nhất!”',132798,0,null,'https://i.docln.net/lightnovel/covers/s447-f0a304f0-7ce4-4255-ad00-7b8a701614b6-m.jpg'),
(DEFAULT,19,'Ato Sakurai','2017','Breakthrough with the Forbidden Master','   “So với thời chúng ta, thế hệ bây giờ chả đáng tin chút nào” họ bảo, “Thêm nữa, Chẳng phải nó là con trai của anh hùng sao?” nghe thật phiền phức.
Đã mười năm trôi qua kể từ khi trận chiến giữa con người và ma tộc kết thúc. Tất cả con cái của những người anh hùng đều đã trưởng thành.
Một trong số họ, Earth, là một thanh niên tài năng, và mọi người đều mong cậu sẽ trở thành một chiến binh như cha cậu và bảo vệ đất nước này, nhưng Earth lúc nào cũng cảnh giác với cái danh hiệu của cha cậu.
Một ngày nọ, Earth đã rất sốc khi tìm thấy thanh kiếm của cha mình, thứ từng được dùng để đánh bại Quỷ Vương, bị giấu kín bên trong căn biệt thự của nhà cậu.
Bởi bên trong nó chính là linh hồn không thể siêu thoát của tên Đại Quỷ Vương và vẫn tiếp tục lang thang khắp thế giới.
Vì lí do nào đó, chỉ mình cậu có thể nhìn thấy linh hồn Đại Quỷ Vương và tên Đại Quỷ Vương đã chiếm lấy cậu qua thanh kiếm.
Ngày qua ngày, cậu đều buộc phải cùng chung sống với linh hồn Đại Quỷ Vương, họ đã sống một cuộc đời sẻ chia kì lạ, rồi bỗng nhiên tên Đại Quỷ Vương bảo cậu.
“Ta có mối thù với cha ngươi. Nếu ngươi muốn chống lại cha ngươi và cả thế giới này. Ta sẽ giúp ngươi. Ta rảnh mà.”
Earth nhận được sự chỉ dạy đặc biệt từ Đại Quỷ Vương chỉ để chống lại cha mình và cả thế giới.
Và rồi, vào một ngày nào đó. Cha mẹ anh hùng, những người anh hùng trong quá khứ, mối tình đầu của cậu, nàng công chúa bạn thuở nhỏ, những thiên tài của thời đại, và cả thế giới đều sẽ chấn động.
',151668,0,null,'https://i.docln.net/lightnovel/covers/s7015-6401f25d-b5cb-4f58-bf5e-09ea9dc07ce3-m.jpg'),
(DEFAULT,16,'Mishima Yomu','2014','Sevens','    Một người anh trai bị cô em gái của mình đánh bại trong cuộc chiến giành quyền thừa kế và bị đuổi khỏi nhà. Mất hết mọi thứ và bị thương nặng đến mức bất tỉnh, trong cơn mê man cậu nghe được những giọng nói mơ hồ, cùng với giọng của ông nội quá cố của bản thân (?), chuyện gì sẽ xảy ra với cậu?
',309069,0,null,'https://4.bp.blogspot.com/-SfvDenZRZrk/W3Uf4bf783I/AAAAAAABiIM/0Xj67F0v-A8lBBzYUHfwhBQuKq8uptSawCHMYCw/w215/default.jpg'),
(DEFAULT,16,'Shinkou Shotou','2017','Arafoo Kenja No Isekai Seikatsu Nikki','     Ông chú trung niên chết đi với vị thế top player trong game, kẻ đã hạ gục boss cuối Evil God.
Chuyển sinh sang thế giới khác cùng sức mạnh overpower giết chết cả thánh thần.
Bắt đầu hành trình mới nơi thế giới mới.
Thế giới mới với nền văn minh ma pháp lạc hậu, hãy chuẩn bị run rẩy, cúi đầu trước bước chân chinh phạt của hiền giả FA 40 tuổi.
""Ờh, tôi chỉ muốn kiếm mảnh vườn để trồng trọt chăn nuôi sống yên lành thôi ! Có bánh mì ăn là hạnh phúc rồi...""',392933,0,null,'https://i.docln.net/lightnovel/covers/s3838-a4521050-9e8b-4357-880e-fd792c76705b-m.jpg'),
(DEFAULT,14,'Hitsuji Gamei','2016','Ankoku kishi monogatari~Yuusha wo taosu tameni Maou ni Shoukansaremashita~','    Đây là huyền thoại về anh main được triệu hồi qua thế giới khác để bảo vệ ma vương khỏi anh hùng.
Tóm lại là: Kuroki bị bất ngờ triệu hồi sang thế giới khác. Người(?) triệu hồi Kuroki lại là Ma vương, Modes. Và, lãnh thổ của Ma vương đang trên bờ vực bị sụp đổ vì Anh Hùng.
Ma vương Modes, người mang trên mình ấn tượng hung bạo, cuối đầu trước Kuroki: ""XIN HÃY GIÚP CHÚNG TÔI, SAVIOR-DONO!!""
Kuroki quyết định giúp Ma vương bởi một số lí do.....',97196,0,null,'https://i.docln.net/lightnovel/covers/s6260-d6a03e86-607b-488b-b867-ee0f03fae4e9-m.jpg'),
(DEFAULT,13,'Jee Gab Song','2016','The Novel ''s Extra','    Khi thức dậy, Kim Hajin nhận ra mình đang ở một thế giới quen thuộc, nhưng trong một cơ thể lạ hoắc.
Thế giới bên trong cuốn tiểu thuyết cậu viết nên, nhưng đã bị drop và sẽ không bao giờ được hoàn thành.
Bản thân cậu, vị tác giả nắm giữ quyền lực tối cao, lại trở thành một nhân vật phụ vô danh làm nền cho chính chuyện - và đó cũng là manh mối duy nhất có thể đưa cậu trở về thế giới của mình.
Thêm nữa, thế giới này lại không hoàn toàn giống với thế giới mà cậu đã sáng tạo nên.',271109,0,null,'https://i.docln.net/lightnovel/covers/s3311-0d40daef-0249-43f0-a004-22ea021d49b4-m.jpg'),
(DEFAULT,20,'Kumanano','2014','Kuma Kuma Kuma Bear','   Yuna, một cô gái 15 tuổi bắt đầu chơi trò chơi định dạng VRMMO đầu tiên trên thế giới.
Cô đã nhận được hàng tỷ Yên từ tiền cổ phiếu, và quyết định ""đóng đô"" luôn trong nhà, không đi học đến trường nữa.
Hôm nay, một bản cập nhật lớn đã tới tay người chơi. Cô ấy nhận được bộ trang phục Gấu quý hiếm, không-thể-chuyển-giao-cho-người-khác.
Nhưng bộ đồ ấy làm cô quá mắc cỡ, đến nỗi cô cũng không dám mặc nó trong game.
Hơn thế nữa, khi trả lời khảo sát về bản cập nhật cũng như tình hình khởi động lại game, cô nhận ra mình đã xuất hiện ở một thế giới khác trong bộ trang phục gấu.
Đây là đâu ? Một lá thư từ Thần ư ? Một thế giới khác sao ?
Nếu cô mặc bộ đồ Gấu vào, cô sẽ là 1 cheater; và nếu cởi nó ra, cô chỉ là một cô gái bình thường mà thôi. Và cô sẽ làm bất kỳ những gì mình muốn theo ý của cô. Cuộc hành trình mới của Yuna đã bắt đầu như vậy đấy.
',44409,0,null,'https://i.docln.net/lightnovel/covers/s1879-d83f75fe-da56-476b-b30c-a712a1408ae9-m.jpg'),
(DEFAULT,20,'Azumi Kei','2017','Otonari no Tenshi-sama ni Itsu no Aida ni ka Dame Ningen ni Sareteiru ken','Amane Fujimiya là một học sinh bình thường không có gì nổi bật. Người hàng xóm của căn chung cư nơi cậu sống là nữ thiên thần dễ thương số 1 của trường, một vẻ đẹp không tì vết và chỉ có thể được miêu tả bằng từ ""thánh nữ"" – Shiina Mahiru. Amane dù là hàng xóm của cô nhưng cho đến bây giờ vẫn chưa nói chuyện lần nào. Sau một lần gặp cô gái thiên thần ấy thút thít dưới trời mưa:
""Tôi đến trả lại đồ hôm trước mượn của cậu đây. À mà này, dọn phòng đi. Nhìn như bãi rác ấy.""
""Không phải chuyện của cậu.""
Mối quan hệ với một nữ thần độc miệng, khởi nguồn từ việc cho mượn ô. Từ bị cảm lạnh và được ai đó chăm sóc, đến việc nấu ăn cho ai đó vì họ chẳng biết quan tâm đến sức khỏe mình, và rồi hai người cùng ấy ấy (làm việc nhà)...
',178841,0,null,'https://i.docln.net/lightnovel/covers/s5257-ae71b593-7ce4-449f-96d1-b485792002f1-m.jpg'),
(DEFAULT,16,'Tappei Nagatsuki','2012','Re:Zero kara Hajimeru Isekai Seikatsu','     Câu chuyện xoay quanh cậu thiếu niên Natsuki Subaru và năng lực Trở Về Từ Cõi Chết cậu nhận được sau khi bị dịch chuyển tới một thế giới song song, thứ giúp cậu quay ngược thời gian để thay đổi số phận nghiệt ngã của chính cậu và những người xung quanh, cũng như cứu giúp nữ chính của mình là Emilia.',207447,0,null,'https://2.bp.blogspot.com/-qTd74A5Bbmk/WO2v0yFjsOI/AAAAAAAAJ88/58sGw4_hp_Y/w215/series_190.jpg');

Insert into with_genre 
values
(1,1),
(1,2),
(1,8),
(1,10),
(1,13),
(1,41),
(2,2),
(2,3),
(2,9),
(2,31),
(2,8),
(3,1),
(3,2),
(3,3),
(3,5),
(3,8),
(3,9),
(3,32),
(3,37),
(3,13),
(3,33),
(3,41),
(3,16),
(4,5),
(4,26),
(4,28),
(4,32),
(4,41),
(5,1),
(5,2),
(5,3),
(5,5),
(5,10),
(5,27),
(6,1),
(6,2),
(6,3),
(6,8),
(6,10),
(6,27),
(6,28),
(6,16),
(6,22),
(6,32),
(6,5),
(6,41),
(7,1),
(7,8),
(7,29),
(8,2),
(8,3),
(8,8),
(8,10),
(8,27),
(8,6),
(8,33),
(8,41),
(8,13),
(8,1),
(8,4),
(8,16),
(8,30),
(8,32),
(9,1),
(9,2),
(9,8),
(9,32),
(9,41),
(9,13),
(9,5),
(9,16),
(10,1),
(10,2),
(10,3),
(10,8),
(10,22),
(10,27),
(10,37),
(10,32),
(10,33),
(10,41),
(10,10),
(10,13),
(10,34),
(10,40),
(11,1),
(11,3),
(11,8),
(11,10),
(11,28),
(11,32),
(11,36),
(11,37),
(11,41),
(11,17),
(11,30),
(11,13),
(12,1),
(12,2),
(12,3),
(12,8),
(12,33),
(12,37),
(12,13),
(12,5),
(12,38),
(12,16),
(12,22),
(13,1),
(13,2),
(13,3),
(13,8),
(13,10),
(13,17),
(13,27),
(13,33),
(13,32),
(14,1),
(14,5),
(14,3),
(14,8),
(14,10),
(14,2),
(14,41),
(14,27),
(15,1),
(15,2),
(15,3),
(15,5),
(15,8),
(15,13),
(15,32),
(15,36),
(15,27),
(15,6),
(15,9),
(15,10),
(15,16),
(16,1),
(16,2),
(16,3),
(16,6),
(16,8),
(16,10),
(16,27),
(16,32),
(16,41),
(16,13),
(17,1),
(17,3),
(17,5),
(17,8),
(17,26),
(17,28),
(17,14),
(18,1),
(18,2),
(18,3),
(18,8),
(18,31),
(18,33),
(18,13),
(18,16),
(18,9),
(19,3),
(19,27),
(19,28),
(19,33),
(20,3),
(20,5),
(20,8),
(20,12),
(20,22),
(20,27),
(20,13),
(20,39),
(20,41),
(20,26),
(20,38),
(20,1),
(20,2);

Insert into read
values
(8,1,'Hết cứu',4),
(3,2,'Mong đọc xong truyện này được A',3),
(5,3,'Hết cứu',4),
(3,4,'Mong đọc xong truyện này được A',4),
(3,5,'Hết cứu',4),
(17,6,'Mong đọc xong truyện này được A',5),
(13,7,'Hết cứu',2),
(20,8,'Mong đọc xong truyện này được A',4),
(7,9,'Hết cứu',5),
(6,10,'Mong đọc xong truyện này được A',1),
(5,11,'Hết cứu',4),
(13,12,'Mong đọc xong truyện này được A',4),
(5,13,'Hết cứu',5),
(15,14,'Mong đọc xong truyện này được A',4),
(3,15,'Hết cứu',5),
(5,16,'Mong đọc xong truyện này được A',3),
(11,17,'Hết cứu',2),
(12,18,'Mong đọc xong truyện này được A',2),
(3,19,'Hết cứu',2),
(8,20,'Mong đọc xong truyện này được A',5),
(3,1,'Hết cứu',4),
(11,2,'Mong đọc xong truyện này được A',1),
(17,3,'Hết cứu',5),
(18,4,'Mong đọc xong truyện này được A',3),
(16,5,'Hết cứu',5),
(4,6,'Mong đọc xong truyện này được A',5),
(11,7,'Hết cứu',4),
(6,8,'Mong đọc xong truyện này được A',5),
(4,9,'Hết cứu',3),
(11,10,'Mong đọc xong truyện này được A',3),
(19,11,'Hết cứu',2),
(12,12,'Mong đọc xong truyện này được A',3),
(6,13,'Hết cứu',1),
(6,14,'Mong đọc xong truyện này được A',3),
(14,15,'Hết cứu',4),
(16,16,'Mong đọc xong truyện này được A',1),
(12,17,'Hết cứu',3),
(5,18,'Mong đọc xong truyện này được A',1),
(11,19,'Hết cứu',5),
(4,20,'Mong đọc xong truyện này được A',3),
(7,1,'Hết cứu',2),
(14,2,'Mong đọc xong truyện này được A',4),
(7,3,'Hết cứu',2);

Insert into favorite_genre
values
(1,15,1),
(1,13,2),
(1,8,3),
(1,23,4),
(1,29,5),
(2,17,1),
(2,18,2),
(2,9,3),
(2,37,4),
(2,40,5),
(3,24,1),
(3,9,2),
(3,15,3),
(3,35,4),
(3,20,5),
(4,16,1),
(4,7,2),
(4,42,3),
(4,33,4),
(4,22,5),
(5,28,1),
(5,17,2),
(5,16,3),
(5,27,4),
(5,12,5),
(6,18,1),
(6,13,2),
(6,35,3),
(6,12,4),
(6,29,5),
(7,42,1),
(7,6,2),
(7,28,3),
(7,2,4),
(7,39,5),
(8,16,1),
(8,19,2),
(8,26,3),
(8,20,4),
(8,3,5),
(9,13,1),
(9,19,2),
(9,11,3),
(9,28,4),
(9,32,5),
(10,35,1),
(10,42,2),
(10,26,3),
(10,38,4),
(10,20,5),
(11,7,1),
(11,25,2),
(11,16,3),
(11,31,4),
(11,38,5),
(12,25,1),
(12,31,2),
(12,2,3),
(12,14,4),
(12,15,5),
(13,7,1),
(13,26,2),
(13,33,3),
(13,3,4),
(13,10,5),
(14,4,1),
(14,33,2),
(14,8,3),
(14,15,4),
(14,11,5),
(15,32,1),
(15,15,2),
(15,10,3),
(15,9,4),
(15,4,5),
(16,11,1),
(16,8,2),
(16,23,3),
(16,1,4),
(16,37,5),
(17,26,1),
(17,27,2),
(17,28,3),
(17,20,4),
(17,2,5),
(18,40,1),
(18,21,2),
(18,19,3),
(18,36,4),
(18,16,5),
(19,11,1),
(19,42,2),
(19,6,3),
(19,12,4),
(19,5,5),
(20,4,1),
(20,27,2),
(20,10,3),
(20,9,4),
(20,3,5);